from pathlib import Path
r=Path('/home/administrator/projects/hexalith/agents/_bmad-output/implementation-artifacts/tests/owner-delivery-2026-10-08')
content={
'ext-parties-1.md':'The shared retained-history reader owns newly serialized closed event payloads until a successful stream result transfers them. Final authority/custody withdrawal, source change, exclusive expiry and cancellation discard and clear accumulated arrays; temporary serialized response-size probes are also cleared. Successful closed output, stored ciphertext and provider input remain exact. The current history class passes 59 cases; the selected Server lane passes 165 and Client lane 109, including prior read regressions. No Parties domain, retention policy or owner Local runner changed.',
'ext-conv-ai-1.md':'Both standalone deletion delivery and exact acknowledgement lookup now use one thirty-second SDK operation budget, with an optional TimeProvider preserving existing caller composition. Provider invocation and noncooperative Tasks are bounded separately from the pump continuation. Abandoned results cannot initiate a later attempt, Submit, acknowledgement or quarantine write. An already invoked idempotent source command may finish only its original durable outcome. Thirty-two suspended invocation/task and cancellation/deadline schedules execute through actual serialized Conversation source; original receiver lookup after restart and existing dispatcher/backfill cases retain consecutive acknowledgement behavior. The selected pump/backfill lane passes 66 cases, with a clean normal Debug build using the explicit sibling EventStore graph. Production worker, receiver and namespace authorities remain unestablished.',
'ext-secrets-1.md':'Signing, direct delivery and key lifecycle actor entries share one thirty-second monotonic budget through private admission, trust, independent journal/state checks and terminal release. StateManager calls stay on the actor turn; an unfinished abandoned state Task excludes subsequent actor calls until actual completion. Late save/journal schedules retain exact admitted Unknown originals and pins, permit only independently authorized original recovery and never repeat Sign/Release/Execute. Completed originals survive withheld replies and serialized restart. Replay profile calls and coordinator factory acquisition use their existing bounded helper. Private credentials enforce strict 2048-byte UTF-8 identity carriers before grant/key or canonical use, retaining exact closed fingerprints/tags/nonces and key cleanup. The selected seven-class custody lane passes 235 cases. The actual guard/subscriber/protection/coordinator replacement vectors preserve the original compromise block while ordinal 2 awaits activation, reconcile an independently proved no-effect blocked disposition before/after dispatch or a completed blocked-activation reply, retain original phase outcomes across restart/lost replies, and complete healthy ordinal 3 once with zero compromised-key reservations.',
'ext-host-1.md':'The shared atomic append client explicitly owns and retires its captured payload copy after every started provider borrower actually finishes; abandoned providers retain unchanged original input until completion, then clear the captured copy once. Caller payload bytes and exact keyed content intent remain unchanged. Optional CausationId uses the existing strict 2048-byte carrier guard. The Client atomic class passes 29 cases. The exact typed/default-unavailable blocked-replacement phase and independent proof ports grant no dispatch, reservation, physical effect or fresh signature. Actor state-I/O exclusion bounds caller release without asserting backend isolation qualification. No AppHost source/resource, runtime enrollment or owner Local runner was changed.'}
common='''[Revision 6 exact commands, current source hashes, preserved before bytes and focused results](resumed-20261008T171001Z/revision-6/README.md) supersede only these corrected source claims. Prior packet bytes are archived in revision-6/owner-packets/before/agents. Four selected lanes contain **575 distinct passing cases**, with no failures/skips/errors/not-run and four clean normal Debug/local-reference builds; repeated historical attempts are excluded. Root full Local matrix and the next fresh independent three-layer review remain pending. The nine surviving requirements are source/focused verified; rejected B6/B10/E2 and moot B11 were not implemented. Runtime authorities/providers/backends/replicas/nonrollback anchors/isolation/all-copy destruction/restore/enrollment/Live qualification remain unestablished. Original Story 5.4 stays draft/backlog, parent in-progress, four dependencies Uncommitted, complete TargetVersionOrCommit and accepted compatibility command TBD. Accepted Branch B, 365-day effective-at/exclusive-expiry policy, L/S/O/H/R, catalogue, dedicated service Party and named human approval remain unchanged. No Git/submodule mutation, deployment, Live invocation or external message occurred.'''
for name,body in content.items():
 p=r/name;p.write_text(p.read_text().rstrip()+'\n\n## Engineering review revision 6 — 2026-10-09\n\n'+body+'\n\n'+common+'\n')
