from pathlib import Path
from datetime import datetime,timezone
import json,hashlib,shutil,re,collections,xml.etree.ElementTree as E
ROOT=Path('/home/administrator/projects/hexalith'); A=ROOT/'agents';D=A/'_bmad-output/implementation-artifacts/tests/owner-delivery-2026-10-08'; S=D/'resumed-20261008T171001Z'; R=S/'revision-7'; V=S/'root-revision6-current-review-20261009T075124Z'
NOW=datetime.now(timezone.utc).isoformat(); EMPTY=hashlib.sha256(b'').hexdigest()
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def write(n,v):(R/n).write_text(json.dumps(v,indent=2)+'\n')
def copy(p,d):d.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(p,d);assert sha(p)==sha(d)
ordered=json.loads((R/'ordered-baselines.json').read_text());prefix=json.loads((S/'revision-6/ordered-baselines.json').read_text());assert len(ordered)==148 and len(prefix)==142 and ordered[:142]==prefix
previous=json.loads((S/'revision-6/artifact-hashes.json').read_text());assert sha(S/'revision-6/artifact-hashes.json')=='7302f5e7d09059ddf17f24517df6fb1e724cd3e68cd8bcc461dcb6158aad98aa'
for f in previous['files']:assert sha(f['path'])==f['sha256'],f
before=[];absence=[];hash_only=[];first={}
for index,c in enumerate(ordered):
 data=json.loads(Path(c).read_text())
 for f in (data if isinstance(data,list) else data.get('files',data.get('sources',[]))):
  bc=f.get('beforeCopy',f.get('copy'));expected=f.get('beforeSha256',f.get('sha256'))
  if bc:
   p=Path(bc);p=p if p.is_absolute() else Path(c).parent/p;assert p.is_file() and expected and sha(p)==expected,(c,f)
   before.append(dict(capture=c,beforeCopy=str(p),sha256=expected,freshRevision7=index>=142))
  elif f.get('existed',f.get('exists')) is False or f.get('newFile') is True:
   if expected:assert expected==EMPTY,(c,f)
   absence.append(dict(capture=c,repository=f.get('repository'),relativePath=f.get('relativePath'),sourcePath=f.get('path'),beforeCopy=None,sha256=EMPTY,basis='Explicit absence/empty-byte basis; no supplied before copy.'))
  else:hash_only.append(dict(capture=c,sourcePath=f.get('path'),expectedSha256=expected,suppliedBeforeCopy=False))
  if index>=142:first.setdefault((f['repository'],f['relativePath']),dict(f,capture=c))
files=[]
for (repo,rel),f in sorted(first.items()):
 p=ROOT/repo/rel;exists=p.is_file();current=sha(p) if exists else EMPTY;changed=exists!=f['existed'] or exists and current!=f['sha256'];dst=R/'after'/repo/rel
 if exists:copy(p,dst)
 files.append(dict(repository=repo,relativePath=rel,sourcePath=str(p),existedBefore=f['existed'],existsNow=exists,beforeSha256=f['sha256'] or EMPTY,currentSha256=current,changed=changed,firstRevision7Capture=f['capture'],beforeCopy=f['beforeCopy'],afterCopy=str(dst) if exists else None,beforeBasis='supplied exact before copy' if f['existed'] else 'explicit absence/empty bytes'))
assert len(files)==21 and all(f['changed'] for f in files)
write('current-owned-source.json',dict(capturedUtc=NOW,scope='Only explicitly captured revision7 source/test/four packet paths; all current bytes and earliest fresh before copies.',uniqueCapturedPaths=len(files),changedPaths=len(files),files=files,unusedAbsentCapturedSourcePaths=[]))
review=json.loads((V/'review-input.json').read_text());allowed={f['sourcePath'] for f in files};changes=[]
for f in review['inputs']:assert sha(f['path'])==f['sha256'],f
for f in review['files']:
 if f.get('reviewCopy') and Path(f['reviewCopy']).is_file():assert sha(f['reviewCopy'])==f['currentSha256'],f
 p=Path(f['sourcePath']);current=sha(p) if p.is_file() else EMPTY
 if current!=f['currentSha256']:changes.append(dict(sourcePath=str(p),reviewedSha256=f['currentSha256'],currentSha256=current,withinRevision7CapturedPath=str(p) in allowed))
external=json.loads((S/'root-revision7-authorization/concurrent-drift-classification.json').read_text())
external_by_path={f['path']:f for f in external['classifications']}
for p,f in external_by_path.items():assert sha(p)==f['currentSha256'] and sha(f['preservedCopy'])==f['currentSha256'],f
outside=[f for f in changes if not f['withinRevision7CapturedPath']]
assert {f['sourcePath'] for f in outside}<=(set(external_by_path)|{str(D/'README.md')}),outside
write('final-reviewed-source-comparison.json',dict(capturedUtc=NOW,reviewInput=str(V/'review-input.json'),reviewInputSha256=sha(V/'review-input.json'),reviewedPaths=len(review['files']),changes=changes,outsideRevision7CapturedPaths=outside,externalClassification=str(S/'root-revision7-authorization/concurrent-drift-classification.json'),externalBytesPreserved=True,outsideOwnershipAttribution='Six documented formatting-only paths preserved without attribution; any global README is root-owned. No whole concurrent workspace immutability claim.'))
protected=json.loads((S/'revision-3/root-protected-interim-audit.json').read_text());checks=[]
for f in protected['checks']:assert sha(f['path'])==f['sha256'];checks.append(dict(f,currentSha256=sha(f['path'])))
spec=A/'_bmad-output/implementation-artifacts/spec-5-4-owner-prerequisites.md';frozen=hashlib.sha256(re.search(rb'<frozen-after-approval[^>]*>[\s\S]*?</frozen-after-approval>',spec.read_bytes()).group(0)).hexdigest();assert frozen==protected['frozenParentSha256']
write('preservation.json',dict(capturedUtc=NOW,orderedCaptures=len(ordered),preservedPrefixCaptures=142,exactPrefixUnchanged=True,reviewedPrefixCaptureHashesMatch=True,suppliedBeforeCopiesChecked=len(before),freshSuppliedBeforeCopiesChecked=sum(f['freshRevision7'] for f in before),suppliedBeforeCopiesMatch=True,beforeCopies=before,absentRows=absence,historicalHashOnlyRows=hash_only,captureHashes=[dict(path=p,sha256=sha(p)) for p in ordered],protectedChecks=checks,frozenParentSha256=frozen,currentParentSha256=sha(spec),parentStatus='in-progress',humanApproval='accepted; separately authorized revision7 only',baselineCommit=protected['baselineCommit'],reviewLoopIteration=7,previousRevisionArtifactsChecked=len(previous['files']),revision6ArtifactManifestSha256=sha(S/'revision-6/artifact-hashes.json'),concurrentExternalWork='All six classified current formatting snapshots remain exact; no restoration or ownership attribution.'))
raw=json.loads(Path('/tmp/revision7-command-ledger.json').read_text());assert raw['missingActualCompletion']==raw['ambiguous']==[];commands=raw['commands'];assert len(commands)==25
for c in commands:
 original=Path(c['originalLog']);p=R/'evidence'/original.name;copy(original,p);c.update(archivedLog=str(p),archivedLogSha256=sha(p),logCompletedUtc=datetime.fromtimestamp(original.stat().st_mtime,timezone.utc).isoformat())
 if c['argv'][1]=='build':
  text=p.read_text();success='Build succeeded.' in text;assert c['completionExitCode']==(0 if success else 1)
  c['recordedResult']=dict(buildSucceeded=success,normalDebugAnalyzersAndXmlChecks=True,localProjectReferences=True,warningSummary=re.findall(r'\d+ Warning\(s\)',text)[-1:],errorSummary=re.findall(r'\d+ Error\(s\)',text)[-1:])
 else:
  original_xml=Path(c['argv'][c['argv'].index('-result-xml')+1]);x=R/'evidence'/original_xml.name;copy(original_xml,x);a=E.parse(x).getroot().find('assembly');stats={k:int(a.get(k,'0')) for k in ['total','passed','failed','skipped','errors','not-run']};assert stats['total']>0 and c['completionExitCode']==(0 if stats['failed']==stats['errors']==0 else 1)
  c.update(originalXml=str(original_xml),archivedXml=str(x),archivedXmlSha256=sha(x),recordedResult=stats,executedNonempty=True)
write('commands.json',dict(scope='Exact actual dotnet argv/cwd/tool start and completion exit/chunk/call/timestamp; copied verbatim logs/XML independently hashed. Output-only source reads excluded. No engineering full root matrix.',commands=commands,exactDotnetInvocations=len(commands),extractor=str(R/'extract-revision7-commands.py'),sessionSource='/home/administrator/.codex/sessions/2026/10/08/rollout-2026-10-08T22-00-23-01a11d1a-47b5-72c2-8f83-badb7d4ac2cc.jsonl'))
selected=[('server-final','joint-green','joint-green-build'),('platform-final','private-wait-green','private-wait-green-build-second'),('client-final','client-final','client-final-build'),('conversations-final','conversation-green','conversation-green-build')]
lanes=[];distinct={};links=[]
for name,test,build in selected:
 x=R/'evidence'/('revision7-'+test+'.xml');b=R/'evidence'/('revision7-'+build+'.log');log=x.with_suffix('.log');tests=E.parse(x).getroot().findall('.//test');a=E.parse(x).getroot().find('assembly')
 assert tests and all(t.get('result')=='Pass' for t in tests) and all(int(a.get(k,'0'))==0 for k in ['failed','skipped','errors','not-run'])
 assert 'Build succeeded.' in b.read_text() and '0 Warning(s)' in b.read_text() and '0 Error(s)' in b.read_text()
 cs=[c for c in commands if c.get('archivedXml')==str(x) and c['archivedLog']==str(log) and c['completionExitCode']==0];bs=[c for c in commands if c['archivedLog']==str(b) and c['completionExitCode']==0];assert len(cs)==len(bs)==1
 c=cs[0];links.append(dict(lane=name,testToolCallId=c['toolCallId'],testTimestamp=c['timestamp'],actualExit=0,completionToolCallId=c['completionToolCallId'],completionToolChunkId=c['completionToolChunkId'],log=str(log),logSha256=sha(log),xml=str(x),xmlSha256=sha(x),buildToolCallId=bs[0]['toolCallId'],buildLog=str(b),buildLogSha256=sha(b),buildActualExit=0))
 for t in tests:
  key=t.get('type'),t.get('name');assert key not in distinct;distinct[key]=dict(name=t.get('name'),type=t.get('type'),method=t.get('method'),result='Pass',xml=str(x),sourceFile=t.get('source-file'),sourceLine=t.get('source-line'))
 lanes.append(dict(lane=name,passed=len(tests),failed=0,skipped=0,errors=0,notRun=0,seconds=a.get('time'),classes=dict(sorted(collections.Counter(t.get('type') for t in tests).items())),buildLog=str(b),testLog=str(log),xml=str(x)))
assert len(distinct)==400
write('final-focused-results.json',dict(scope='Current four focused owning lanes only; modeled authority/providers and controlled clocks. Overlap excluded; root current Local matrix/review pending.',distinctPassedCases=400,lanes=lanes,tests=sorted(distinct.values(),key=lambda t:(t['type'],t['name'])),exactSuccessfulCommandLinks=links))
notes={'revision7-history-grant-red.xml':'19 actual prior-source failures:18 initial/final grant vector cancellation/deadline/invalid-carrier cases and one detached-snapshot reuse case.','revision7-namespace-red.xml':'Two actual inconsistent revision-one install/restored failures; registered growth control passes.','revision7-joint-red.xml':'19 actual failures across22 selected cases: oversized outcome allocation, blocked request/guard collection and disabled-entry cancellation. Three already-safe traversal/request paths pass.','revision7-private-wait-red.xml':'Only disabled coordinator original cancellation genuinely failed. Eight prior clock cases used watchdog-only TimeoutException assertions, insufficient to prove helper timeout; do not claim them as B5 failed-before proof. Final assertions require the helper-specific completed operation, and actual actor cases suspend admission and cover negative/infinite-sentinel durations.','revision7-conversation-red.xml':'Two standalone actual synchronous worker invocation cancellation cases genuinely fail; existing serialized deleted-open predicate control passes.'}
historical=[]
for c in commands:
 if c['completionExitCode']==0:continue
 f=dict(timestamp=c['timestamp'],workingDirectory=c['workingDirectory'],argv=c['argv'],log=c['archivedLog'],logSha256=c['archivedLogSha256'],actualExitCode=c['completionExitCode'],actualCompletionChunkId=c['completionToolChunkId'],result=c['recordedResult'])
 if c.get('archivedXml'):f.update(xml=c['archivedXml'],interpretation=notes[Path(c['archivedXml']).name])
 else:f.update(interpretation='Owned test compile/API/nullability/analyzer correction; retained historical failure, no diagnostic checks weakened.',firstDiagnostic=next((line for line in Path(c['archivedLog']).read_text().splitlines() if ': error ' in line),None))
 historical.append(f)
write('historical-attempts.json',dict(scope='Exact historical failures preserved, genuine source failures distinguished from test carrier/analyzer corrections and insufficient preliminary watchdog assertions. No synthetic red/mutation or aggregate unique failing count claimed.',attempts=historical))
alltypes={f['type'] for f in distinct.values()};classes=[]
for f in files:
 if '/tests/' not in f['sourcePath'] or not f['sourcePath'].endswith('.cs'):continue
 old=Path(f['beforeCopy']).read_text();current=Path(f['sourcePath']).read_text();pattern=r'^public\s+(?:(?:sealed|partial|abstract)\s+)*class\s+(\w+)';olds=re.findall(pattern,old,re.M);news=re.findall(pattern,current,re.M);assert news==olds
 ns=re.search(r'^namespace\s+([\w.]+)',current,re.M)[1];assert all(ns+'.'+name in alltypes for name in news)
 classes.append(dict(sourcePath=f['sourcePath'],beforePublicClasses=olds,currentPublicClasses=news,newPublicTestClasses=[],currentFocusedClasses=[ns+'.'+name for name in news]))
write('required-class-audit.json',dict(capturedUtc=NOW,newPublicTestClasses=[],editedPublicTestClassesRemainExisting=True,allEditedClassesActuallyExecutedInCorrectProject=True,paths=classes,ownerRunnerSourceChanges=False,priorRequiredMappingsPreserved=True,prior44ClassExecutionRequirement='Preserved; root recomputes all44 and actual current full matrix execution after handoff.'))
resolutions=[('E4','Initial/final grant bounded detached capture and caller-first denial; safe history ownership unchanged.','server-final'),('B3','Revision-one complete and initial roster equality; restored malformed denial; registered growth and original retry retained.','client-final'),('B4','Existing16MiB outcome bound before both backend lookup clones; independently authenticated originals unchanged.','server-final'),('E1','Only pure owned joint request capture moved inside deadline; no late authority/transaction continuation.','server-final'),('E2','Existing target Count/1000 guard remains inside bounded pure target capture before guard proof/effect.','server-final'),('B5','One remaining duration per private wait; nonpositive values throwTimeout before WaitAsync, with safe late completion/actor original.','platform-final'),('B6','All demonstrated disabled coordinator/guard/transaction entries check original caller/budget first; active restrictive defaults retained.','server-final'),('E3','Standalone source/delivery worker30s acquisition budget covers synchronous invocation/task and final release.','conversations-final'),('B1','Standalone verifier30s cumulative budget covers worker/lookup/target/final authority; actual admission caller covered.','conversations-final'),('V1','Actual serialized Open-but-IsDeleted conversation is inactive and excluded from complete current count; production predicate unchanged.','conversations-final')]
write('finding-status.json',dict(capturedUtc=NOW,revision=7,triageInput=str(V/'current-review-triage.json'),triageSha256=sha(V/'current-review-triage.json'),requiredFindings=[dict(finding=fid,status='implemented and current focused verified; fresh root full Local and three-layer review pending',change=change,focusedEvidence=next(l['xml'] for l in lanes if l['lane']==lane),additionalFocusedEvidence=next(l['xml'] for l in lanes if l['lane']=='platform-final') if fid=='B6' else None) for fid,change,lane in resolutions],rejectedCurrentFindings=['B2','B7','B9','B10'],mootUnverifiedFinding='B8; no fabricated zero-target authority or deferred append',sourceWorkIncomplete=[],newProductionOrTestTypes=[],fullRootVerification='pending',nextThreeLayerReview='pending',productionQualification='unestablished'))
contexts=[spec,A/'_bmad-output/specs/spec-story-5-4-dependency-unblock/owner-implementation-plan.md',A/'_bmad-output/specs/spec-story-5-4-dependency-unblock/parties-identity-contract.md',A/'_bmad-output/planning-artifacts/external-dependency-register.md',V/'blind-final.md',V/'edge-final.json',V/'verification-final.md',V/'current-review-triage.json',S/'root-revision7-authorization/concurrent-drift-classification.json']
write('context-loaded.json',dict(scope='Complete current spec including appended B6 clarification, all frontmatter context files and all three exact current reports/triage/preservation read before their dependent implementation.',files=[dict(path=str(p),sha256=sha(p),lines=len(p.read_text().splitlines())) for p in contexts]))
write('engineering-handoff.json',dict(capturedUtc=NOW,status='stable source engineering handoff prepared; final packaged check separate',spec=str(spec),specSha256=sha(spec),revision=7,sourceEngineer='owner_rederivation',orderedBaselines=str(R/'ordered-baselines.json'),orderedCaptureCount=len(ordered),preservedExactPrefixCount=142,freshUnits=len(ordered)-142,uniqueCapturedSourceTestPacketPaths=len(files),changedSourceTestPacketPaths=len(files),focusedDistinctPassedCases=400,focusedLanes=lanes,exactDotnetCommands=len(commands),selectedLaneCommandLinksVerified=4,currentBuilds='Four clean normal Debug/local-reference builds, zero warnings/errors; analyzer/XML defaults retained.',findingStatus=str(R/'finding-status.json'),commands=str(R/'commands.json'),sourceHashes=str(R/'current-owned-source.json'),preservation=str(R/'preservation.json'),historicalAttempts=str(R/'historical-attempts.json'),priorPacketBytes=str(R/'owner-packets/before/agents'),verificationMap=str(R/'required-class-audit.json'),reviewFreezeOwner='Root independently freezes cumulative source, reads complete delta, runs three fresh review layers and mandatory full Local matrix.',remainingWork=['Fresh root complete Local matrix and three-layer review.','Current enrollment/authority, qualified provider/backend/replica/isolation/nonrollback/all-copy destruction/restore/Live acceptance unestablished.','OriginalStory5.4 draft/backlog; parent in-progress; four dependencies Uncommitted, complete target/accepted full command TBD.'],limits=['Finite budgets release callers, never qualify provider forced termination/reclamation or backend isolation.','Existing unfinished actor state-I/O exclusion and exact independently retained recovery remain mandatory.','Modeled authorities/backends/providers do not establish runtime enrollment or owner acceptance.'],preserved='Frozen intent/protected source, exact142 capture prefix and all previous artifacts, documented concurrent bytes without attribution. No source/artifact edits after final delivery.'))
(R/'README.md').write_text('''# Engineering review revision 7 — stable source handoff

All ten surviving requirements are source implemented and focused verified. Four selected owning lanes contain **400 distinct passing cases**: Server173, Platform89, Client24 and Conversations114, with no errors/failures/skips/not-run and four clean normal Debug/local-reference builds. [Exact commands](commands.json) retain every actual cwd/argv/tool timestamp/completion exit/chunk plus copied log/XML hashes; [selected results](final-focused-results.json) link each selected build/log/XML to its exact successful command. Engineering did not run the root full matrix.

[Resolutions](finding-status.json) cover bounded detached initial/final history grants, exact revision-one namespace rosters, backend outcome bounds before cloning, pure transaction/guard target captures, safe private remaining-time construction, disabled-entry caller cancellation, standalone worker/verifier cumulative budgets, and actual serialized deleted-open catalogue/count exclusion. Existing source/closed buffer ownership, independently authenticated original outcomes, current authority and all prior positive protocol units remain preserved. [Historical attempts](historical-attempts.json) distinguish genuine prior-source failures from test carrier/analyzer corrections and an insufficient initial watchdog-only assertion; those eight preliminary clock cases are not claimed as B5 failed-before evidence. Final helper assertions require its completed timeout, and actual actor admission remains suspended while checking the safe unavailable outcome. No mutation result is claimed.

[Ordered captures](ordered-baselines.json) preserve the exact142-entry revision6 prefix and append six fresh units, totaling148. [Current owned source](current-owned-source.json) covers21 changed source/test/packet paths. [Preservation](preservation.json) independently checks every supplied before copy, historical absence/hash-only basis, previous revision artifacts and protected/frozen intent. Six documented concurrent formatting paths remain at their current independently archived bytes, without ownership attribution or rollback; [reviewed-source comparison](final-reviewed-source-comparison.json) records that distinction. No new C# type/public test class or owner runner was added; [correct-project execution](required-class-audit.json) confirms every edited test class executes while preserving root's44-class requirement.

Four owner packets append truthful current source/runtime status; their exact prior complete bytes remain in owner-packets/before/agents. The preceding revision6 root matrix/reviews are historical after current edits. Fresh revision7 root full Local verification and three independent review layers remain pending. Current authorities/enrollment/providers/backends/replicas/nonrollback anchors/isolation/all-copy destruction/restore/Live acceptance remain unestablished. OriginalStory5.4 stays draft/backlog, parent in-progress, four dependencies Uncommitted, complete target/accepted compatibility command TBD. Accepted Branch B,365-day effective-at/exclusive-expiry/no-renewal,L/S/O/H/R,catalogue,dedicated service Party and named approval remain unchanged. Rejected B2/B7/B9/B10 and moot unverified B8 receive no implementation/deferred append. No Git/submodule operation, deployment, Live invocation or external message occurred.

A finite budget releases callers and never establishes forced provider reclamation or backend isolation. Existing safe actor state-I/O exclusion and exact original independent recovery remain mandatory. Root owns cumulative freeze, complete delta/packet inspection, fresh review and full Local verification. [Engineering handoff](engineering-handoff.json) and handoff-verification.json record the stable package check; no source or packaged-artifact edit follows final delivery.
''')
print(json.dumps(dict(captures=len(ordered),prefix=142,freshUnits=len(ordered)-142,changedPaths=len(files),beforeCopies=len(before),freshBeforeCopies=sum(f['freshRevision7'] for f in before),commands=len(commands),selectedPasses=400,historicalAttempts=len(historical),outsideOwnedChanges=outside),indent=2))
