"""Record the user's explicit extra-cycle approval without changing frozen intent."""
import datetime
import hashlib
import json
from pathlib import Path
import re

resume = Path(__file__).resolve().parent
workspace = resume.parents[4]
spec = workspace / '_bmad-output/implementation-artifacts/spec-5-4-owner-prerequisites.md'
before = spec.read_bytes()
assert hashlib.sha256(before).hexdigest() == 'e510ad862debf73db6fc8dd96c4a7dff580247909ee73b001f4a48dc0bdcae08'
assert b'review_loop_iteration: 6' in before
out = resume / 'root-revision6-authorization'
out.mkdir(exist_ok=False)
(out / 'parent-before-authorization.md').write_bytes(before)
frozen = re.search(rb'<frozen-after-approval.*?</frozen-after-approval>', before, re.S).group()
append = '''

## Spec Change Log — Authorized engineering revision 6, 2026-10-09

The user answered "yes" to the concrete revision-5 handoff's request for one additional implementation-and-review cycle. This explicitly overrides the five-loop checkpoint for revision6 only. Preserve the truthful accumulated review_loop_iteration:6; do not reset it, rerender the skill, repeat this approval request, or infer unlimited further loopbacks. This authorizes the nine source fixes already prepared for review; it grants no runtime enrollment, live execution, retention change, new owner acceptance or full parent completion. Historical review-halt.json remains an immutable record of the checkpoint; this section and the new authorization record supersede its pending decision.

Revision-5 B2/B4/B5/B8/E1 exposed technical omissions in whole-operation admission/state lifetime, standalone source delivery, bounded private credential carriers, captured append-buffer ownership and issued-but-unactivated compromise recovery. All are outside frozen intent. B1/B3/B7/B9 remain mandatory direct corrections in the same re-derivation. The source preservation instruction takes precedence over blanket rollback: retain the existing working owner units and re-derive only demonstrated faulty fragments in place from fresh before captures. The reviewed395 paths still exactly match the revision-5 freeze before this authorization; concurrent unrelated source is preserved.

KEEP: every positive correction and constraint in revisions1–5 and the complete prior Spec Change Log. Keep the independently conditional admitted-original journal and retained prospective bytes, read-only denial, immutable Unknown/terminal results and original receipts/signatures/dispatch, same-tenant reservation and immediate compromised-key refusal, conditional source/outbox transactions, exact canonical owner+operation identity, finite complete namespace and independently authenticated resumable reconciliation/acknowledgement progress. Keep actor-free expired continuity, detached immediate unprotect ownership, single-use safe abandonment cleanup, v2 protection bytes and cumulative carrier bound, retired-epoch refusal, final post-registration execution fence, spool recorder/capacity readiness and independently retained never-invoked signing denial. Preserve normal Debug/local references/analyzers/XML; every user/concurrent edit; accepted Branch B/365-day effective-at/exclusive expiry/no renewal/L-S-O-H-R/catalogue/service Party/named approver inputs; original Story5.4/sprint/register/policy/frozen intent; and disabled runtime defaults. Preserve prior rejected universal phase proofs, durable canary cleanup/fresh expired-grant authorization, worker interval expansion, invented Extensions collection callbacks and raw command hashes. No blanket reset, Git mutation, submodule operation, deployment, external message or unavailable consuming live seam.

### Required engineering revision 6

Read the three final reports and individual current-review-triage.json at tests/owner-delivery-2026-10-08/resumed-20261008T171001Z/root-revision5-current-review-20261009T024940Z. The sole source engineer remains owner_rederivation if it can be continued; if unavailable, step03's context-free implementation handoff provides the replacement sole source engineer. Work sequentially in dependency order, applying these nine independently classified outcomes. The latest requirements supersede only the faulty fragments described here; previous positive requirements remain in force. Do not implement B6/B10/E2 (carried rejected claims) or B11 (unverified operational-diagnostics claim, moot at loopback).

- E1: in ../eventstore/src/Hexalith.EventStore.Server/Security/GovernanceScopeGuardReducer.cs, ../eventstore/src/Hexalith.EventStore.Server/Security/DeletionConsumptionActor.cs, ../platform/src/Hexalith.Platform.Custody/DeletionBatchExecutionCoordinator.cs and their narrowly necessary Contracts/guard port/authority adapters, retain the independently proved original compromise block while an issued replacement awaits protection activation. Add the minimal authenticated no-effect reconciliation needed when that replacement key is subsequently compromised, including before any replacement dispatch exists. Ordinary dispatch/activation/consumption still requires its full original evidence and must remain denied for a compromised key. A distinct private typed/default-unavailable no-effect phase may settle an already issued replacement as blocked under independent exact guard-issue and protection-original proof; it grants no dispatch, reservation, physical effect or fresh signing. Correlate tenant/seal/batch/manifest, original protection block receipt, issued signed replacement/canonical request/attestation ordinal, exact source revocation and current independently authenticated key-block comparison. Advance or retain both owners' attestation correlation coherently so a later healthy successor is exactly the next original, without skipping an ordinal, reusing an issued ordinal or fabricating a dispatch receipt. Recover only original retained phase outcomes after lost acknowledgement/restart. Preserve the valid reservation-winner terminal recovery, unaffected original blocks and exact event deduplication. Given ordinal1 is blocked, ordinal2 is issued and its key is revoked before or after replacement dispatch but before activation, when actual guard/subscriber/protection/coordinator owners resume across serialized restart and lost replies, then ordinal2 can reconcile only an independently proved blocked disposition and healthy ordinal3 can complete once; zero compromised-key reservations and zero duplicate physical consumption. Execute omitted/foreign/stale/forged reconciliation-proof denial and unchanged original ledger/receipt checks.
- B2: in ../platform/src/Hexalith.Platform.Custody/DeletionCapabilitySigningActor.cs, CustodyKeyLifecycleActor.cs, ExportKeyDeliveryActor.cs and narrowly necessary shared technical deadline/state helpers, apply one existing thirty-second monotonic operation budget from each entry through initial/final operation permission, signing trust, independent state/journal authority and terminal release. Bound pure external provider invocation/await using the existing deadline, keeping immutable captured arguments and observed late faults. StateManager invocation and actor continuations remain on the turn; never Task.Run an actor method, StateManager mutation, journal/result persistence or a resumed released turn. Where an in-turn state-store Task must be abandoned to release the method, retain an explicit per-actor in-flight state-I/O lifetime boundary: later calls fail closed promptly without sharing/clearing/mutating that StateManager while the abandoned I/O is unfinished. Clear the boundary only on actual completion, observe faults, reconfirm exact independent original journal/state on recovery, and prevent old I/O/results from overwriting a later admitted owner outcome. This boundary grants no persistence authority and is not durable backend isolation qualification. A genuinely uncertain effect keeps its exact existing Unknown/pin/reservation and lookup-only recovery; timeout never manufactures Denied/NotDelivered/nonperformance. Given admission, trust, journal/state await or final admission is suspended, when the same whole budget expires, then the actor call releases without late terminal evidence; subsequent calls return promptly and no actor-state continuation resumes from late provider completion. Execute actual actor end-state/restart schedules with suspended state I/O and late completion, restrictive originals, exact recovery and no second Sign/Release/Execute. Final completed originals must still be preserved even when response permission is withdrawn or late.
- B4: in ../conversations/src/Hexalith.Conversations.Server/Agents/ConversationDeletionDeliveryPump.cs, its publication adapter and the existing shared SDK deadline, give both standalone DeliverAsync and LookupAcknowledgementAsync one thirty-second whole-operation budget from entry, using a narrowly necessary optional TimeProvider testing/composition parameter while preserving existing caller constructors. Bound external authority/receiver/source invocation and noncooperative returned Tasks through the shared helper. Never abandon the entire mutable pump continuation: once the budget/caller terminates, late provider results cannot initiate another attempt, receiver Submit, acknowledgement/quarantine write or terminal evidence. A command already invoked may resolve its original independently idempotent durable outcome; timeout cannot erase that attempt or report acknowledgement. Keep exact current source/delivery worker checks, target rollover/original lookup, consecutive source acknowledgement and current dispatcher composition. Given actual standalone source, authority, target, lookup or submit Tasks/invocations are suspended with CancellationToken.None, when the operation budget expires, then both entries return their existing Unavailable form promptly with no late phase continuation; caller cancellation keeps its original token. Execute later original lookup/restart and dispatcher-positive cases without renewed attempts or false prefix progress.
- B5: in ../platform/src/Hexalith.Platform.Custody/PrivateOwnerOperationAuthenticator.cs and only necessary carrier validation helpers, use the already existing owner identifier limit of2048 UTF-8 bytes per identity string, with strict UTF-8/malformed-surrogate rejection. Apply it to all required scope identifiers, the four exact machine claim values, current profile identifiers, returned grant AuthorityReference and signing-key version before their provider/canonical/HMAC use; preserve the closed64-character fingerprint/tag/nonce checks. Validate caller-controlled scope and claims before grant/key provider invocation; validate returned independent profile/grant/key identifiers before building canonical credential bytes. Use bounded pure claim/scope capture if necessary to preserve the existing whole-operation budget; do not allocate unbounded matching-claim arrays. Retain duplicate/missing claim denial, dedicated-machine classification, exact scope/issuer/audience/grant/revision, current/retained key, lifetime/rotation and final current confirmation. This reuses an operational carrier bound and changes no production authority or capacity policy. Given an oversized or malformed scope/claim, when Issue/Authorize is called, then it denies before grant/key invocation; independently oversized returned profile/grant/key data denies before credential release and owned keys/buffers are safely cleared. Execute valid boundary text and prior success/withdrawal/deadline regressions.
- B8: in ../eventstore/src/Hexalith.EventStore.Client/Streams/DirectoryAtomicAppendClient.cs and IAtomicDirectoryAppendOwner/IDirectoryAtomicAppendAuthority ownership documentation, establish explicit read-only borrowing of the captured request's Payload array only until each provider Task actually terminates. Providers may not retain/share/mutate that owned array after their operation; any qualified internal retained representation must have its own independently governed ownership. Capture failure, no owner/authority, completed denial/success/fault and caller cancellation/deadline must retire the caller-side copy; clear it only when all actually started borrowers have finished, with at-most-once cleanup. Preserve the original caller payload and exact content-intent HMAC; no plaintext request persistence or raw content hash. A late authority/owner call receives its original unchanged input until completion, but cannot resume client evidence or another effect after outer termination. Given arrays captured by authority/owner on each normal and abandoned path, then discarded captured copies clear at the safe boundary, original caller arrays remain exact, and one uncertain append resolves only original lookup. Cover capture failure after copying, retained input during suspension and eventual completion cleanup; no artificial Dictionary callbacks.
- B1: in ../platform/src/Hexalith.Platform.Custody/TrustedEnvelopeReplayVerifier.cs, bound both initial/final profiles.GetCurrent via the existing PrivateOwnerOperationDeadline and check that same budget immediately before release. Keep exact immutable replay receipt first-seen/ReplayRetention, current authentication/profile/time and original caller cancellation. Execute suspended first/final calls, expiry and cancellation/clock advancement during the final call; no late authenticated envelope or provider-triggered canceled success.
- B3: in ../platform/src/Hexalith.Platform.Custody/DeletionBatchExecutionCoordinator.cs, resolve both existing synchronous factories inside the existing deadline as pure factory-result acquisition. Only after successful bounded acquisition may owner methods run. Execute actually suspended signer and protection factories, caller cancellation/deadline, late result, and unchanged successful actual-owner completion; no late signing/dispatch/activation/protection continuation.
- B7: in ../eventstore/src/Hexalith.EventStore.Client/Streams/DirectoryAtomicAppendClient.cs, validate a non-null Command.CausationId with the existing strict ValidText2048-byte guard before copying/releasing the captured request. Null remains optional; non-whitespace/ULID-safe identifier rules remain unchanged. Execute oversized, malformed UTF-16, null and valid maximum-bound causation through actual client admission/owner call counts and preserved caller request. No Guid parsing or unkeyed metadata/content digest.
- B9: in ../eventstore/src/Hexalith.EventStore.Server/Security/RetainedIdentityHistorySourceReader.cs, retain ownership of newly serialized closed event Payload arrays until a successful stream result actually transfers them to its caller. Clear every accumulated owned array on all unsuccessful/canceled exits, including later source/head/current authority/custody/certificate/expiry/response-bound denial. Clear any temporary serialized response-bound probe after measuring it; do not clear successful returned closed event arrays, original actor ciphertext or borrowed provider inputs. Keep the existing immediate readable-buffer and abandoned-unprotect cleanup. Given at least one closed attribution event has been accumulated before final denial/cancellation, then its discarded owned bytes clear while the caller receives no stream; successful closed history and stored originals remain exact. Execute final authority/custody withdrawal, source change, exclusive expiry and cancellation with actual array ownership observation, plus successful transfer.

### Revision 6 source tasks and acceptance

These checked source units do not complete or narrow the full parent Tasks & Acceptance above. Root will mark them only from its own diff and actual executed evidence.

- [ ] E1 — authenticated blocked-replacement reconciliation through actual owners, before/after dispatch, lost reply and restart, healthy next successor and no compromised effect.
- [ ] B2 — bounded actor admission/trust/journal/state lifetime and final release, safe in-flight StateManager boundary, immutable original recovery and no repeated effect.
- [ ] B4 — bounded standalone pump Deliver/Lookup invocation and all waits, exact original durable source state and no late phase continuation.
- [ ] B5 — existing finite strict UTF-8 private carrier bounds before provider/canonical use, exact grants and successful boundary vectors.
- [ ] B8 — captured append request borrowing/retirement and exactly once safe normal/abandoned cleanup, no original mutation.
- [ ] B1 — bounded replay profile calls and final terminal budget/caller check.
- [ ] B3 — bounded owner factory acquisition with no late owner continuation.
- [ ] B7 — optional causation uses the existing carrier validation before release.
- [ ] B9 — discarded closed history/temporary bound-probe cleanup and successful output ownership transfer.
- [ ] Engineering package — truthful before/current captures, exact completed command records/log/XML/hashes, genuine failed-before evidence, affected normal builds and mapped executed classes, all four updated truthful owner packets and stable final handoff.

Given any correction above, when its focused normal Debug/local-reference/analyzer/XML build and actual test classes execute, then all relevant current cases pass with no skipped/errors/not-run; assertions verify durable/ownership end-state rather than implementation-mirroring checks. Given a compile or provider protocol blocker, record it exactly and complete other independent authorized units; do not waive the owning build or claim root verification. Given a stable revised package, root independently reads the entire new delta, checks the complete cumulative freeze and capture/artifact hashes, runs all three fresh review layers before handling results, and executes the mandatory full Local matrix with fresh source/protected-state snapshots. Earlier passing matrix/selected tests remain historical after edits, with overlap excluded from unique totals. Current full parent and runtime qualification remain incomplete until their distinct requirements are actually satisfied.

Start from the exact125-entry tests/owner-delivery-2026-10-08/resumed-20261008T171001Z/revision-5/ordered-baselines.json (SHA25667dd34772eb01aa84d78d03e8621bec2e2faedd2624956afb0b2b26d5c272c2f). Append fresh revision-6 capture units for every edited existing/new source/test/runner/packet path using capture-owned-before.py; retain that complete prior prefix and every prior before copy/hash. Root-owned frozen review input and all historical engineering packages remain read-only. Existing owner packets are the four previously captured agent-side docs in revision-5/owner-packets; archive their exact current bytes before update. Keep any new test class in the correct existing owner Local map and prove actual nonempty class execution. Package revision-6 under tests/owner-delivery-2026-10-08/resumed-20261008T171001Z/revision-6, including finding-status.json, ordered-baselines.json, commands.json, current-owned-source.json, selected focused results, source/artifact hashes, preserved historical failures and stable engineering-handoff.json. Each selected log/XML links to its actual command cwd/argv/start/finish/completion exit. No synthetic red or claimed mutation result without genuine execution. Do not mutate source/artifacts after final delivery.

Concurrent unrelated EventStore logical-snapshot/rewitness changes caused the last root Server refresh to fail with twoCS0246 errors at DaprLogicalSnapshotRewitnessTests.cs:606/611. Preserve all that external work; freshly check the current owning build after it settles, do not silently reuse previous binaries or take ownership of unrelated edits. Required source mappings include the entire previously covered44 owner test classes plus any newly added actual classes. Root owns full verification and source review; engineering runs only focused affected checks. Existing Aspire CLI resources=[] baseline is already captured; no AppHost source change or new live invocation is required for these units. Original Story5.4 remains draft/backlog; four dependencies stay Uncommitted with complete targets/accepted commandsTBD. Accepted authorizations persist; the worker/signer runtime configuration location is unknown, so do not reask it or invent enrollment/trust/backend qualification.
'''
newline = '\r\n' if b'\r\n' in before else '\n'
after = before + append.replace('\n', newline).encode()
assert re.search(rb'<frozen-after-approval.*?</frozen-after-approval>', after, re.S).group() == frozen
spec.write_bytes(after)
now = datetime.datetime.now(datetime.timezone.utc).isoformat()
record = dict(capturedUtc=now, userReply='yes', approvedAction='one additional implementation-and-review cycle for the nine saved revision-5 fixes',
              reviewLoopIterationRetained=6, overrideScope='revision6 only; no counter reset or unlimited loop approval',
              specBeforeSha256=hashlib.sha256(before).hexdigest(), specAfterSha256=hashlib.sha256(after).hexdigest(),
              frozenIntentSha256=hashlib.sha256(frozen).hexdigest(), fullParentStatus='accepted in-progress',
              runtimeQualification='unestablished; no new live authorization', originalStorySprintRegisterPolicy='preserved',
              historicalHalt=str(resume/'root-revision5-current-review-20261009T024940Z/review-halt.json'),
              priorCapturePrefixCount=125, currentReviewedOwnedPathsUnchanged=395)
(out/'authorization.json').write_text(json.dumps(record, indent=2)+'\n')
print(json.dumps(record, indent=2))
