from pathlib import Path
import json,hashlib,re,shutil,collections,xml.etree.ElementTree as E
from datetime import datetime,timezone
ROOT=Path('/home/administrator/projects/hexalith');A=ROOT/'agents'
D=A/'_bmad-output/implementation-artifacts/tests/owner-delivery-2026-10-08';S=D/'resumed-20261008T171001Z';R=S/'revision-5';V=S/'root-revision4-current-review-20261009T014502Z'
NOW=datetime.now(timezone.utc).isoformat();EMPTY=hashlib.sha256(b'').hexdigest()
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def write(n,v):(R/n).write_text(json.dumps(v,indent=2)+'\n')
ordered=json.loads((R/'ordered-baselines.json').read_text());assert len(ordered)==125
assert ordered[:114]==json.loads((S/'revision-4/ordered-baselines.json').read_text())
review=json.loads((V/'review-input.json').read_text());assert len(review['inputs'])==114
for f in review['inputs']:assert sha(f['path'])==f['sha256'],f
previous=json.loads((S/'revision-4/artifact-hashes.json').read_text());assert len(previous['files'])==177
for f in previous['files']:assert sha(f['path'])==f['sha256'],f
before=[];absence=[];hash_only=[];first={}
for i,c in enumerate(ordered):
 data=json.loads(Path(c).read_text())
 for f in (data if isinstance(data,list) else data.get('files',data.get('sources',[]))):
  copy=f.get('beforeCopy',f.get('copy'));expected=f.get('beforeSha256',f.get('sha256'))
  if copy:
   p=Path(copy);p=p if p.is_absolute() else Path(c).parent/p
   assert p.is_file() and expected and sha(p)==expected,(c,f)
   before.append({'capture':c,'beforeCopy':str(p),'sha256':expected,'freshRevision5':i>=114})
  elif f.get('existed',f.get('exists')) is False or f.get('newFile') is True:
   if expected:assert expected==EMPTY,(c,f)
   absence.append({'capture':c,'repository':f.get('repository'),'relativePath':f.get('relativePath'),'sourcePath':f.get('path'),'beforeCopy':None,'sha256Basis':'explicit absence, empty bytes','sha256':EMPTY})
  else:hash_only.append({'capture':c,'repository':f.get('repository'),'relativePath':f.get('relativePath'),'sourcePath':f.get('path'),'expectedSha256':expected,'suppliedBeforeCopy':False})
  if i>=114:first.setdefault((f['repository'],f['relativePath']),dict(f,capture=c))
files=[]
for (repo,rel),f in sorted(first.items()):
 p=ROOT/repo/rel;exists=p.is_file();current=sha(p) if exists else EMPTY;changed=exists!=f['existed'] or exists and current!=f['sha256']
 if exists and p.suffix in ['.cs','.ps1']:
  raw=p.read_bytes();assert b'\r\n' in raw and b'\n' not in raw.replace(b'\r\n',b''),p
 dst=R/'after'/repo/rel
 if exists:dst.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(p,dst);assert sha(dst)==current
 files.append({'repository':repo,'relativePath':rel,'sourcePath':str(p),'existedBefore':f['existed'],'existsNow':exists,'beforeSha256':f['sha256'],'currentSha256':current,'changed':changed,'firstRevision5Capture':f['capture'],'beforeCopy':f['beforeCopy'],'afterCopy':str(dst) if exists else None})
assert len(files)==26 and sum(f['changed'] for f in files)==24
unchanged=[f for f in files if not f['changed']];assert {Path(f['sourcePath']).name for f in unchanged}=={'DirectoryAtomicAppendClient.cs','DirectoryAtomicAppendTests.cs'}
write('current-owned-source.json',{'capturedUtc':NOW,'scope':'Explicit revision-5 source/test/four packet capture paths with earliest fresh before bytes and exact current copies. B4 two unchanged restored paths are captured but not attributed as changed source.','uniqueCapturedPaths':26,'changedPaths':24,'files':files,'unchangedRejectedB4Paths':unchanged,'unusedAbsentCapturedSourcePaths':[]})
allowed={f['sourcePath'] for f in files};changes=[]
for f in review['files']:
 p=Path(f['sourcePath']);cur=sha(p) if p.is_file() else EMPTY
 if cur!=f['currentSha256']:changes.append({'sourcePath':str(p),'reviewedSha256':f['currentSha256'],'currentSha256':cur,'withinRevision5CapturedPath':str(p) in allowed})
outside=[x for x in changes if not x['withinRevision5CapturedPath']]
assert {x['sourcePath'] for x in outside}<={str(D/'README.md')},outside
initial=json.loads((R/'previous-reviewed-source-comparison.json').read_text());assert initial['reviewedFiles']==394 and initial['drift']==[]
write('final-reviewed-source-comparison.json',{'capturedUtc':NOW,'reviewInput':str(V/'review-input.json'),'reviewInputSha256':sha(V/'review-input.json'),'reviewedPaths':394,'initialReviewedDrift':[],'changes':changes,'outsideRevision5CapturedPaths':outside,'outsideOwnershipAttribution':'Root-owned global README only, if present. All other current query/event-evolution/replay/concurrent source remains unchanged versus root reviewed snapshot.','initialCheck':str(R/'previous-reviewed-source-comparison.json')})
protected=json.loads((S/'revision-3/root-protected-interim-audit.json').read_text());checks=[]
for f in protected['checks']:assert sha(f['path'])==f['sha256'];checks.append(dict(f,currentSha256=sha(f['path'])))
spec=A/'_bmad-output/implementation-artifacts/spec-5-4-owner-prerequisites.md';assert sha(spec)=='60eb78110670ee4c2bebe3874e8e0b0116141db6af17566cd3309ea3ae6634f3'
frozen=hashlib.sha256(re.search(rb'<frozen-after-approval[^>]*>[\s\S]*?</frozen-after-approval>',spec.read_bytes()).group(0)).hexdigest();assert frozen==protected['frozenParentSha256']
write('preservation.json',{'capturedUtc':NOW,'orderedCaptures':125,'preservedPrefixCaptures':114,'exactPrefixUnchanged':True,'reviewedPrefixCaptureHashesMatch':True,'suppliedBeforeCopiesChecked':len(before),'freshSuppliedBeforeCopiesChecked':sum(f['freshRevision5'] for f in before),'suppliedBeforeCopiesMatch':True,'beforeCopies':before,'absentRows':absence,'historicalHashOnlyRows':hash_only,'captureHashes':[{'path':p,'sha256':sha(p)} for p in ordered],'protectedChecks':checks,'frozenParentSha256':frozen,'currentParentSha256':sha(spec),'parentStatus':'in-progress','humanApproval':'accepted','baselineCommit':protected['baselineCommit'],'reviewLoopIteration':5,'revision4MetadataCorrectionPreserved':True,'revision4ArtifactManifestSha256':sha(S/'revision-4/artifact-hashes.json'),'revision4ArtifactsChecked':177,'frozenScope':'Original Story 5.4 draft/backlog, sprint, date-only four Uncommitted dependencies and accepted Party retention policy unchanged; frozen intent unchanged. No Git mutation/submodule/deployment/Live/external message.','concurrentExternalWork':'Preserved; source outside fresh captures remains at reviewed bytes except any root-owned global README update.'})
raw=json.loads(Path('/tmp/revision5-command-ledger.json').read_text());assert len(raw['commands'])==38 and raw['missingActualCompletion']==raw['ambiguous']==[]
archived={p.name:p for p in R.rglob('revision5-*.log')};commands=raw['commands']
for c in commands:
 p=archived[Path(c['originalLog']).name];assert sha(p)==sha(c['originalLog']);c.update({'archivedLog':str(p),'archivedLogSha256':sha(p),'logCompletedUtc':datetime.fromtimestamp(Path(c['originalLog']).stat().st_mtime,timezone.utc).isoformat()})
 if c['argv'][1]=='build':
  log=p.read_text();success='Build succeeded.' in log;assert c['completionExitCode']==(0 if success else 1)
  c['recordedResult']={'buildSucceeded':success,'normalDebugAnalyzersAndXmlChecks':True,'localProjectReferences':True,'warningSummary':re.findall(r'\d+ Warning\(s\)',log)[-1:] or [],'errorSummary':re.findall(r'\d+ Error\(s\)',log)[-1:] or []}
 else:
  xp=c['argv'][c['argv'].index('-result-xml')+1];x=p.with_suffix('.xml');assert x.is_file() and sha(x)==sha(xp)
  a=E.parse(x).getroot().find('assembly');stats={k:int(a.get(k,'0')) for k in ['total','passed','failed','skipped','errors','not-run']}
  assert c['completionExitCode']==(0 if stats['failed']==stats['errors']==0 else 1)
  c.update({'originalXml':xp,'archivedXml':str(x),'archivedXmlSha256':sha(x),'recordedResult':stats})
write('commands.json',{'scope':'Exact actually executed shell command/dotnet argv/cwd/tool-call timestamp, with actual returned process completion exit/chunk/call/timestamp from this task session. Verbatim logs/XML and hashes corroborate results; logCompletedUtc is final log write time, not exact termination time. Builds sequential; no root full matrix run. The sign-red call returned its test exit before an unrelated stale process poll failed; that actual exit is retained.','commands':commands,'exactDotnetInvocations':38,'sessionSource':str(Path('/home/administrator/.codex/sessions/2026/10/08/rollout-2026-10-08T22-00-23-01a11d1a-47b5-72c2-8f83-badb7d4ac2cc.jsonl'))})
selected=[('server-final','final-focused/revision5-server-final-tests.xml','final-focused/revision5-server-final-build.log'),('platform-final','final-focused/revision5-platform-final-tests.xml','final-focused/revision5-platform-final-build.log'),('payload-path','protected-path-capture/revision5-path-tests.xml','protected-path-capture/revision5-path-build.log'),('client-deadline-regression','final-focused/revision5-client-final-tests.xml','final-focused/revision5-client-final-build.log')]
lanes=[];distinct={};links=[]
for lane,x,b in selected:
 p=R/x;build=R/b;tree=E.parse(p).getroot();a=tree.find('assembly');ts=tree.findall('.//test');assert ts and all(t.get('result')=='Pass' for t in ts)
 assert all(int(a.get(k,'0'))==0 for k in ['failed','skipped','errors','not-run']);assert 'Build succeeded.' in build.read_text() and '0 Warning(s)' in build.read_text() and '0 Error(s)' in build.read_text()
 cs=[c for c in commands if c.get('archivedXml')==str(p) and c['archivedLog']==str(p.with_suffix('.log')) and c['completionExitCode']==0];bs=[c for c in commands if c['archivedLog']==str(build) and c['completionExitCode']==0];assert len(cs)==len(bs)==1,(lane,cs,bs)
 c=cs[0];assert c['archivedLogSha256']==sha(p.with_suffix('.log')) and c['archivedXmlSha256']==sha(p)
 links.append({'lane':lane,'testToolCallId':c['toolCallId'],'testTimestamp':c['timestamp'],'actualExit':0,'completionToolCallId':c['completionToolCallId'],'completionToolChunkId':c['completionToolChunkId'],'log':c['archivedLog'],'logSha256':c['archivedLogSha256'],'xml':str(p),'xmlSha256':sha(p),'buildToolCallId':bs[0]['toolCallId'],'buildLog':str(build),'buildLogSha256':sha(build),'buildActualExit':0})
 for t in ts:
  key=t.get('type'),t.get('name');assert key not in distinct
  distinct[key]={'name':t.get('name'),'type':t.get('type'),'method':t.get('method'),'result':'Pass','xml':str(p),'sourceFile':t.get('source-file'),'sourceLine':t.get('source-line')}
 lanes.append({'lane':lane,'passed':len(ts),'failed':0,'skipped':0,'errors':0,'notRun':0,'seconds':a.get('time'),'classes':dict(sorted(collections.Counter(t.get('type') for t in ts).items())),'buildLog':str(build),'testLog':str(p.with_suffix('.log')),'xml':str(p)})
assert len(distinct)==426
write('final-focused-results.json',{'scope':'Current selected focused behavior with modeled authorities/providers and controlled clocks; no full root matrix or runtime qualification. Historical/overlapping runs excluded.','distinctPassedCases':426,'lanes':lanes,'tests':sorted(distinct.values(),key=lambda t:(t['type'],t['name'])),'exactSuccessfulCommandLinks':links})
notes={'revision5-history-red-tests.xml':'Five genuine failed-before buffer lifetime regressions; provider-owned original input remains unchanged until termination.','revision5-history-tests.xml':'One assertion-only JSON casing mismatch: successful closed output intentionally uses web serialization; corrected exact expected web bytes. No production lifetime failure remaining.','revision5-signing-red-tests.xml':'Two genuine post-intent trust-loss regressions; uncertain-sign control already passes.','revision5-spool-red-tests.xml':'Three genuine missing recorder/full retained capacity readiness regressions.','revision5-private-red-tests.xml':'Five genuine unbounded initial/final synchronous profile and late release regressions.','revision5-path-red-tests.xml':'First test attempt was too weak: three caller vectors fail, while three deadline vectors falsely accept external watchdog timeout. Retained honestly; not counted as independent genuine red evidence.','revision5-path-red-tests-second.xml':'Six strict genuine traversal GetEnumerator/MoveNext/Current caller/deadline failures; operation must complete before provider release, Count unused.','revision5-registry-red-tests.xml':'One genuine cumulative sealed-copy bound failure; valid within-bound restart control passes.','revision5-aggregate-red-tests.xml':'Two genuine protection-before-postregistration-fence failures; current-authority control passes.','revision5-epoch-red-tests.xml':'One genuine retired A epoch reactivation failure through actual two-repair owner path after serialization.'}
historical=[]
for c in commands:
 if c['completionExitCode']==0:continue
 row={'timestamp':c['timestamp'],'workingDirectory':c['workingDirectory'],'argv':c['argv'],'log':c['archivedLog'],'logSha256':c['archivedLogSha256'],'actualExitCode':c['completionExitCode'],'actualCompletionChunkId':c['completionToolChunkId']}
 if 'archivedXml' in c:row.update({'xml':c['archivedXml'],'result':c['recordedResult'],'interpretation':notes[Path(c['archivedXml']).name]})
 else:
  diagnostic=next((l for l in Path(c['archivedLog']).read_text().splitlines() if ': error ' in l),None)
  row.update({'firstDiagnostic':diagnostic,'interpretation':'Rejected B4 review premise: concrete Extensions Dictionary cannot accept the proposed supplied interface collection. Original source/test bytes restored; no seam or API added.' if 'atomic' in c['originalLog'] else 'Historical test compilation/analyzer correction, with no checks disabled; superseded by clean normal build.'})
 historical.append(row)
assert len(historical)==13
write('historical-attempts.json',{'scope':'Earlier nonpassing invocations retained verbatim. True source regressions distinguished from assertion-only, weak-watchdog and rejected-review-premise attempts; excluded from current pass count.','genuineFailingBeforeCases':25,'attempts':historical,'V1Evidence':'Two current actual-owner in-flight method-only withdrawal cases. Root preverified the revision-4 20-case mutant gap; engineer did not perform another source mutation or claim a new failed-before run.'})
classrows=[]
alltypes={t['type'] for t in distinct.values()};fullmap=(S/'root-revision4-current-review-20261009T014502Z/root-local-class-mapping-plan-r4.json')
for f in files:
 if '/tests/' not in f['sourcePath'] or not f['sourcePath'].endswith('.cs') or not f['changed']:continue
 old=Path(f['beforeCopy']).read_text();new=Path(f['sourcePath']).read_text();pat=r'^public\s+(?:(?:sealed|partial|abstract)\s+)*class\s+(\w+)';olds=re.findall(pat,old,re.M);news=re.findall(pat,new,re.M);assert set(news)<=set(olds),(f,olds,news)
 ns=re.search(r'^namespace\s+([\w.]+)',new,re.M)[1];assert all(ns+'.'+c in alltypes for c in news)
 classrows.append({'sourcePath':f['sourcePath'],'beforePublicClasses':olds,'currentPublicClasses':news,'newPublicClasses':[],'currentFocusedClasses':[ns+'.'+c for c in news]})
write('required-class-audit.json',{'capturedUtc':NOW,'newPublicTestClasses':[],'editedPublicTestClassesRemainExisting':True,'allEditedClassesActuallyExecutedInCorrectProject':True,'paths':classrows,'ownerRunnerSourceChanges':False,'priorRequiredMappingsPreserved':True,'rootProvisionalMappingPlan':str(fullmap),'rootFullLocalExecution':'pending; root recomputes cumulative execution and maps after source freeze'})
findingrows=[('B7','Detached readable custody result transfer and completed/abandoned one-time clearing; provider input and returned closed output preserved.','server-final','Five true reds; reader/expired source cases plus Client regression pass.'),('E1','Known post-intent never-invoked trust loss retains exact Denied; uncertain attempted signing remains Unknown and lookup-only.','platform-final','Two true reds and uncertain control; actual consumer and serialized restart retain original.'),('B1','Existing recorder is required for readiness.','platform-final','Empty and acknowledged no-recorder denials; qualified controls preserved.'),('B2','Readiness refuses existing full retained RecordBound without purging originals.','platform-final','10000 acknowledged originals remain queryable/idempotent; new observation refuses.'),('B3','Initial/final synchronous profile acquisition bounded with final elapsed-time release check and one abandonment cleanup.','platform-final','Five true reds; caller/deadline and late completion deny credential; existing exact grant/key/HMAC cases pass.'),('B5','Pure manifest traversal runs inside original helper budget with safe owned-material cleanup; Count unused.','payload-path','Six strict true reds for GetEnumerator/MoveNext/Current; no late registry/key/encryption/writer effect.'),('B6','Cumulative sealed ciphertext capture refuses beyond existing 32MiB pending-state carrier budget before copying each carrier.','server-final','One true red and valid within-bound serialized restart; no independent state/effect call on oversized restore.'),('B8','Actual aggregate fence rechecked after registration and before EventPersister protection/staging.','server-final','Two true reds; withdrawn/expired preserves durable namespace and no event/protection; current control appends once.'),('E2','Every retained retired repair epoch excluded from successor activation.','server-final','One true red; actual A→B then B→A refused after serialization, new C succeeds, immutable historical results survive.'),('V1','Test-only suspended Deliver and Lookup exact method credential withdrawal coverage.','platform-final','Two actual-owner vectors preserve durable Delivered/ObservedAt/expiry, refuse release and restore exact lookup with no repeated Release; production checks unchanged.')]
statuses=[{'finding':fid,'status':'implemented and current focused verified; root full Local/fresh independent review pending','change':change,'verification':proof,'focusedEvidence':next(l['xml'] for l in lanes if l['lane']==lane)} for fid,change,lane,proof in findingrows]
write('finding-status.json',{'capturedUtc':NOW,'revision':5,'triageInput':str(V/'current-review-triage.json'),'triageSha256':sha(V/'current-review-triage.json'),'requiredFindings':statuses,'rejectedCurrentFindings':[{'finding':'B4','reason':'Root concrete caller correction: concrete Dictionary, unreachable supplied blocked collection; captured paths unchanged, no seam/API.'},{'finding':'B9','reason':'Disproved by root triage; no patch or defer.'},{'finding':'B10','reason':'Prior low-complexity rejection carried unchanged; no patch or defer.'}],'sourceWorkIncomplete':[],'fullRootVerification':'pending','nextThreeLayerReview':'pending','productionQualification':'unestablished','priorRejectedDirectionsPreserved':['Universal guard-proof expansion','Durable canary cleanup/expired original authority relaxation','Worker interval-policy expansion','Raw arbitrary command/Extensions unkeyed hash']})
write('engineering-handoff.json',{'capturedUtc':NOW,'status':'stable source engineering handoff prepared; final packaged check in handoff-verification.json','spec':str(spec),'specSha256':sha(spec),'revision':5,'sourceEngineer':'owner_rederivation','orderedBaselines':str(R/'ordered-baselines.json'),'orderedCaptureCount':125,'preservedExactPrefixCount':114,'freshUnits':11,'uniqueCapturedSourceTestPacketPaths':26,'changedSourceTestPacketPaths':24,'unchangedB4Paths':2,'focusedDistinctPassedCases':426,'focusedLanes':lanes,'exactDotnetCommands':38,'selectedLaneCommandLinksVerified':4,'currentBuilds':'Four clean normal Debug/local-reference builds, zero warnings/errors; analyzers/XML defaults retained. Full root Local matrix never run by engineer.','findingStatus':str(R/'finding-status.json'),'commands':str(R/'commands.json'),'sourceHashes':str(R/'current-owned-source.json'),'preservation':str(R/'preservation.json'),'previousReviewedSourceComparison':str(R/'final-reviewed-source-comparison.json'),'historicalAttempts':str(R/'historical-attempts.json'),'ownerPackets':['ext-parties-1.md','ext-conv-ai-1.md','ext-secrets-1.md','ext-host-1.md'],'priorPacketBytes':str(R/'owner-packets/before/agents'),'verificationMap':str(R/'required-class-audit.json'),'reviewFreezeOwner':'Root freezes cumulative manifest/diff using all 125 ordered captures, launches next three fresh independent reviewers and executes complete mandatory Local matrix.','remainingWork':['Root complete Local matrix and next independent three-layer review.','Current authorities/enrollment, qualified providers/backends/replicas/nonrollback anchors/isolation/all-copy destruction/restore/Live acceptance unestablished.','Story5.4 draft/backlog, parent in-progress, four dependencies Uncommitted; complete TargetVersionOrCommit and accepted full compatibility command TBD.'],'limits':['Deadline bounds release the caller but do not forcibly terminate/reclaim blocked providers or establish deployment capacity.','Custody plaintext result ownership requires detached exclusive transfer as documented; provider-shared buffers cannot qualify that contract.','Modeled independent authority/backend/provider ports do not establish actual runtime composition.'],'preserved':'Frozen intent, protected story/sprint/register/policy, prior revision-4 metadata correction and all external work. No source/artifact edits after stable final handoff.'})
readme='''# Engineering review revision 5 — stable source handoff

All ten surviving findings are implemented and focused verified. B4 is false/rejected after root traced the concrete Dictionary caller; its two captured files retain exact before bytes, with no test seam or public API. B9/B10 and all prior rejected directions remain rejected. The sole-source spec and frozen intent are unchanged by this engineer.

The four selected lanes contain **426 distinct passing cases**, with no failures, skips, errors or not-run cases: Server 156, custody 157, payload protection 33, Client deadline regression 80. Each has a clean normal Debug/local-reference build with zero warnings/errors. [Exact commands](commands.json) record 38 executed dotnet invocations, their actual returned completion exit/chunk/timestamp, cwd and verbatim log/XML hashes. [Current selected results](final-focused-results.json) link every selected build/test to the exact successful command. Repeated historical runs are excluded.

[Finding resolutions](finding-status.json) describe transient plaintext ownership/clearing, known never-invoked signing denial, recorder/capacity readiness, bounded profile/path traversal, cumulative ciphertext capture, post-registration execution fence, retired repair epochs and test-only in-flight private delivery authority. [Historical attempts](historical-attempts.json) retain thirteen earlier nonpassing invocations and distinguish 25 genuine failed-before source cases from assertion, watchdog, compiler and rejected-premise attempts. V1 closes root's preverified mutation gap with two actual suspended private-method withdrawal cases; no additional mutation was claimed.

[Ordered captures](ordered-baselines.json) contain 125 entries, preserving the exact 114-entry revision-4 prefix. Eleven fresh units retain 26 supplied before copies: 24 changed source/test/packet paths and two unchanged B4 paths. [Current path hashes and exact copies](current-owned-source.json), [preservation](preservation.json) and [reviewed-source comparison](final-reviewed-source-comparison.json) verify existing frozen inputs, earlier artifacts and concurrent external source. Original four owner packet bytes are in owner-packets/before/agents; the current four packets append source/runtime truth. No new public test class or owner runner change was added; [correct-project class execution](required-class-audit.json) is recorded.

Root full Local matrix and the next fresh independent three-layer review remain pending. The mandatory complete matrix has never yet run; focused source tests do not establish runtime qualification or complete parent acceptance. Original Story 5.4 stays draft/backlog, parent in-progress, all four dependencies Uncommitted, complete target/accepted compatibility command TBD. Current worker/signer/issuer/role enrollment, providers/backends/replicas/nonrollback anchors/isolation/all-copy destruction/restore/Live qualification remain unestablished. Accepted Branch B, 365-day policy, effective/exclusive expiry, L/S/O/H/R, catalogue, service Party and human approver inputs remain unchanged. No Git/submodule operation, deployment, Live seam or external message occurred.

The deadline releases an abandoned caller; it does not forcibly stop blocked provider execution or qualify resource reclamation. Detached custody buffer transfer is an explicit provider ownership requirement. Root owns cumulative freeze, review and full verification after this handoff. [Engineering handoff](engineering-handoff.json) and the final handoff-verification.json record the packaged source/evidence check. No source or packet edits follow stable final delivery.
'''
(R/'README.md').write_text(readme)
print(json.dumps({'capturedPaths':26,'changedPaths':24,'captures':125,'prefix':114,'suppliedBeforeCopiesChecked':len(before),'freshCopies':sum(f['freshRevision5'] for f in before),'historicalHashOnlyRows':len(hash_only),'historicalAbsenceRows':len(absence),'dotnetCommands':38,'selectedPasses':426,'historicalNonpassing':len(historical),'outsideOwnedChanges':outside},indent=2))
